### ISSUE TITLE
Hierarchy Web Part Fails to Load

### ISSUE THREAD

**Issue by tomkell29** [SharePoint/sp-dev-gdpr-activity-hub#46]
Web Part fails to load and says "something went wrong".
Technical details contains the below:

[SPLoaderError.loadComponentError]:
***Failed to load component "50c8ec09-6a38-4831-a537-fdedd8e560f3" (GdprHierarchyWebPart).
Original error: ***Failed to load entry point from component "50c8ec09-6a38-4831-a537-fdedd8e560f3" (GdprHierarchyWebPart).
Original error: Error loading https://component-id.invalid/50c8ec09-6a38-4831-a537-fdedd8e560f3_0.0.1
	Unable to load script https://publiccdn.sharepointonline.com/metuk.sharepoint.com/sites/GDPR-CDN/GDPR-Files/GDPRActivityHub/gdpr-hierarchy.bundle_40142f7231124f3725487932d34ccbb3.js

***INNERERROR:
***Failed to load entry point from component "50c8ec09-6a38-4831-a537-fdedd8e560f3" (GdprHierarchyWebPart).
Original error: Error loading https://component-id.invalid/50c8ec09-6a38-4831-a537-fdedd8e560f3_0.0.1
	Unable to load script https://publiccdn.sharepointonline.com/metuk.sharepoint.com/sites/GDPR-CDN/GDPR-Files/GDPRActivityHub/gdpr-hierarchy.bundle_40142f7231124f3725487932d34ccbb3.js
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-03.006/sp-pages-assembly_en-us_830f94e81dde185d60d0c487f9f9fc4e.js:326:20910)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-03.006/sp-pages-assembly_en-us_830f94e81dde185d60d0c487f9f9fc4e.js:888:22876)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-03.006/sp-pages-assembly_en-us_830f94e81dde185d60d0c487f9f9fc4e.js:888:15211)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-03.006/sp-pages-assembly_en-us_830f94e81dde185d60d0c487f9f9fc4e.js:888:11208)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2017-11-03.006/sp-pages-assembly_en-us_830f94e81dde185d60d0c487f9f9fc4e.js:888:109888
    at <anonymous>

**Comment by tomkell29** [comment]
This is no longer an issue. Must have been a temporary glitch with SharePoint.
