### ISSUE TITLE
The application appear on Sharepoint but can't use it

### ISSUE THREAD

**Issue by Torture13** [SharePoint/sp-dev-gdpr-activity-hub#52]
Hello, 

I made all the steps with success and uploaded the package to Sharepoint Online. 
When I try to add the application on my page this message appears on Application catalog.

gdpr-starter-kit-client-side-solution
You can't add this app here.
Find out why

Any ideas?
Thanks,

**Comment by Torture13** [comment]
Seems that I could use webparts now . But i get an error 

[SPLoaderError.loadComponentError]:
***Failed to load component "8805cdf9-9e29-4c17-b0a5-797950a6a4bd" (GdprDashboardWebPart).
Original error: ***Failed to load URL 'https://publiccdn.sharepointonline.com/gdprgr.sharepoint.com/sites/CDN/CDNFiles/GDPRActivityHub/gdprstarterkit-gdprdashboardstrings_en-us_dbd0e8fefc585602d88bf6f4fd3bb8b4.js' for resource 'gdprDashboardStrings' in component '8805cdf9-9e29-4c17-b0a5-797950a6a4bd' (GdprDashboardWebPart). There was a problem in the server.

***INNERERROR:
***Failed to load URL 'https://publiccdn.sharepointonline.com/gdprgr.sharepoint.com/sites/CDN/CDNFiles/GDPRActivityHub/gdprstarterkit-gdprdashboardstrings_en-us_dbd0e8fefc585602d88bf6f4fd3bb8b4.js' for resource 'gdprDashboardStrings' in component '8805cdf9-9e29-4c17-b0a5-797950a6a4bd' (GdprDashboardWebPart). There was a problem in the server.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-05.012/sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:295:15366)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-05.012/sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:712:38036)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-05.012/sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:712:43523)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-05.012/sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:712:40250)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-01-05.012/sp-pages-assembly_en-us_18b206dbf5ea8a9da3221367da049861.js:712:12345
    at <anonymous>
